# Generated by Django 3.2.3 on 2021-09-03 15:51

from django.db import migrations, models
import eshop_product.models


class Migration(migrations.Migration):

    dependencies = [
        ('eshop_product', '0008_auto_20210903_2014'),
    ]

    operations = [
        migrations.AlterField(
            model_name='picture',
            name='image',
            field=models.ImageField(upload_to=eshop_product.models.generate_name_file_for_picture, verbose_name='تصویر'),
        ),
    ]
