# Generated by Django 3.2.3 on 2021-09-04 13:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eshop_product', '0009_alter_picture_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='image',
        ),
    ]
